name: Threadfin Beta Build
on:
  push:
    branches:
      - beta
permissions:
  contents: write
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f086349bfa2bd1361f7909c78558e816508cdc10 # v2.8.0
        with:
          egress-policy: audit

      - name: Check out code into the Go module directory
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          ref: beta

      - name: Set up and Build
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version: '1.20'
        id: go
      - run: |
         go mod tidy && go mod vendor
         echo "Building Linux"
         env GOOS=linux GOARCH=amd64 go build -o dist/Threadfin_linux_amd64
